name: CI Symfony 7.3 - Quality Control
on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # On lance un container MySQL pour les tests
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctl, iconv, intl, pdo_mysql # pdo_mysql est requis ici
          coverage: none

      - name: Check Composer Lock
        run: composer validate --no-check-publish

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Lint Symfony Config
        run: |
          php bin/console lint:yaml config
          php bin/console lint:twig templates
          php bin/console lint:container

      - name: Setup Database
        env:
          # On se connecte au service mysql lancé plus haut (127.0.0.1)
          DATABASE_URL: "mysql://root:password@127.0.0.1:3306/symfony_test?serverVersion=8.0"
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPUnit Tests
        env:
          DATABASE_URL: "mysql://root:password@127.0.0.1:3306/symfony_test?serverVersion=8.0"
        run: php bin/phpunit

      - name: Security Check
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          /home/runner/.symfony5/bin/symfony check:security